// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-tS3qPO39OO_V9NETyc0hFo7370Ras5U',
    appId: '1:112514048399:web:31645f99ea2f4ff5a32bfa',
    messagingSenderId: '112514048399',
    projectId: 'lab7-ecaec',
    authDomain: 'lab7-ecaec.firebaseapp.com',
    storageBucket: 'lab7-ecaec.appspot.com',
    measurementId: 'G-21M9PWNW47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP9HCAdTzpkN0cWxvj4MiU6uFx3Rd4Yw0',
    appId: '1:112514048399:android:35dcff93acd49327a32bfa',
    messagingSenderId: '112514048399',
    projectId: 'lab7-ecaec',
    storageBucket: 'lab7-ecaec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmq0VwIW7KuBuPC0WGM5YTD8mhLG7IO7M',
    appId: '1:112514048399:ios:dbd9722b6b38b290a32bfa',
    messagingSenderId: '112514048399',
    projectId: 'lab7-ecaec',
    storageBucket: 'lab7-ecaec.appspot.com',
    iosBundleId: 'com.example.lab7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmq0VwIW7KuBuPC0WGM5YTD8mhLG7IO7M',
    appId: '1:112514048399:ios:5386e5f2ed5e3c05a32bfa',
    messagingSenderId: '112514048399',
    projectId: 'lab7-ecaec',
    storageBucket: 'lab7-ecaec.appspot.com',
    iosBundleId: 'com.example.lab7.RunnerTests',
  );
}
